//Cracked by Kafei
// /d/huanghe/changle/bangjob10000.c
// by aln 2 / 98

// inherit SKILL;

inherit F_CLEAN_UP;

mapping *bangjobs = ({
        ([      "name"  :  "阿拉伯商人",
                "file"  :  "/d/quanzhou/npc/alabo",
                "area"  :  "泉州阿拉伯宅區",
                "type"  :  "殺",
                "bonus" :  10,
                "score" :  4,
        ]),

        ([      "name"  :  "波斯商人",
                "file"  :  "/d/xingxiu/npc/trader",
                "area"  :  "天山腳下",
                "type"  :  "殺",
                "bonus" :  20,
                "score" :  6,
        ]),

        ([      "name"  :  "回回",
                "file"  :  "/d/quanzhou/npc/huihui",
                "area"  :  "清淨寺",
                "type"  :  "殺",
                "bonus" :  15,
                "score" :  8,
        ]),

        ([      "name"  :  "風良",
                "file"  :  "/d/yixing/npc/fengliang",
                "area"  :  "揚州郊外",
                "type"  :  "殺",
                "bonus" :  40,
                "score" :  12,
        ]),

        ([      "name"  :  "沈青剛",
                "file"  :  "/d/huanghe/npc/shen",
                "area"  :  "黃河幫",
                "type"  :  "殺",
                "bonus" :  20,
                "score" :  10,
        ]),

        ([      "name"  :  "吳青烈",
                "file"  :  "/d/huanghe/npc/wu",
                "area"  :  "黃河幫",
                "type"  :  "殺",
                "bonus" :  18,
                "score" :  9,
        ]),

        ([      "name"  :  "馬青雄",
                "file"  :  "/d/huanghe/npc/ma",
                "area"  :  "黃河幫",
                "type"  :  "殺",
                "bonus" :  16,
                "score" :  8,
        ]),

        ([      "name"  :  "錢青健",
                "file"  :  "/d/huanghe/npc/qian",
                "area"  :  "黃河幫",
                "type"  :  "殺",
                "bonus" :  15,
                "score" :  7,
        ]),

        ([      "name"  :  "紅貨",
                "file"  :  "/d/xingxiu/obj/red",
                "type"  :  "尋",
                "bonus" :  12,
                "score" :  4,
        ]),

        ([      "name"  :  "哈密瓜",
                "file"  :  "/d/xingxiu/obj/hamigua",
                "type"  :  "尋",
                "bonus" :  15,
                "score" :  5,
        ]),

        ([      "name"  :  "百草丹",
                "file"  :  "/clone/medicine/nostrum/baicaodan",
                "type"  :  "尋",
                "bonus" :  30,
                "score" :  8,
        ]),

        ([      "name"  :  "雄黃",
                "file"  :  "/clone/medicine/vegetable/xionghuang",
                "type"  :  "尋",
                "bonus" :  30,
                "score" :  8,
        ]),

        ([      "name"  :  "當歸",
                "file"  :  "/clone/medicine/vegetable/danggui",
                "type"  :  "尋",
                "bonus" :  30,
                "score" :  8,
        ]),

        ([      "name"  :  "鯊膽",
                "file"  :  "/clone/medicine/vegetable/shadan",
                "type"  :  "尋",
                "bonus" :  30,
                "score" :  8,
        ]),

        ([      "name"  :  "人蔘果",
                "file"  :  "/clone/medicine/nostrum/renshenguo",
                "type"  :  "尋",
                "bonus" :  60,
                "score" :  16,
        ]),

        ([      "name"  :  "何首烏",
                "file"  :  "/clone/medicine/vegetable/heshouwu",
                "type"  :  "尋",
                "bonus" :  30,
                "score" :  8,
        ]),

        ([      "name"  :  "莽牯朱蛤",
                "file"  :  "/clone/medicine/nostrum/mangguzhuha",
                "type"  :  "尋",
                "bonus" :  30,
                "score" :  8,
        ]),

        ([      "name"  :  "無常丹",
                "file"  :  "/clone/medicine/nostrum/wuchangdan",
                "type"  :  "尋",
                "bonus" :  30,
                "score" :  8,
        ]),

        ([      "name"  :  "三清換質丹",
                "file"  :  "/clone/medicine/nostrum/huanzhidan",
                "type"  :  "尋",
                "bonus" :  30,
                "score" :  8,
        ]),

        ([      "name"  :  "孟婆茶",
                "file"  :  "/clone/medicine/nostrum/mengpotea",
                "type"  :  "尋",
                "bonus" :  30,
                "score" :  8,
        ]),

        ([      "name"  :  "老山參",
                "file"  :  "/clone/medicine/vegetable/laoshanshen",
                "type"  :  "尋",
                "bonus" :  30,
                "score" :  8,
        ]),

        ([      "name"  :  "人蔘",
                "file"  :  "/clone/medicine/vegetable/renshen",
                "type"  :  "尋",
                "bonus" :  40,
                "score" :  10,
        ]),

        ([      "name"  :  "通天草",
                "file"  :  "/d/wuliang/obj/cao",
                "type"  :  "尋",
                "bonus" :  10,
                "score" :  2,
        ]),

        ([      "name"  :  "狗皮膏藥",
                "file"  :  "/clone/medicine/nostrum/gaoyao",
                "type"  :  "尋",
                "bonus" :  10,
                "score" :  3,
        ]),

        ([      "name"  :  "狗肉湯",
                "file"  :  " /d/guanwai/npc/obj/gouroutang",
                "type"  :  "尋",
                "bonus" :  20,
                "score" :  8,
        ]),

        ([      "name"  :  "長白山旅遊圖",
                "file"  :  "/d/guanwai/npc/obj/map",
                "type"  :  "尋",
                "bonus" :  20,
                "score" :  8,
        ]),

        ([      "name"  :  "白雲石",
                "file"  :  "/d/xingxiu/obj/yushi",
                "type"  :  "尋",
                "bonus" :  10,
                "score" :  3,
        ]),

        ([      "name"  :  "藍玉缽",
                "file"  :  "/d/xingxiu/obj/lanyubo",
                "type"  :  "尋",
                "bonus" :  10,
                "score" :  3,
        ]),

        ([      "name"  :  "無錫醬排骨",
                "file"  :  "/d/wuxi/npc/obj/paigu",
                "type"  :  "尋",
                "bonus" :  10,
                "score" :  3,
        ]),

        ([      "name"  :  "梅花",
                "file"  :  "/d/lingxiao/obj/mei",
                "type"  :  "尋",
                "bonus" :  10,
                "score" :  3,
        ]),

        ([      "name"  :  "龜蛇酒壺",
                "file"  :  "/d/yueyang/npc/obj/guishejiu",
                "type"  :  "尋",
                "bonus" :  10,
                "score" :  3,
        ]),
        
        ([      "name"  :  "兔肉",
                "file"  :  "/d/baituo/npc/obj/turou",
                "type"  :  "尋",
                "bonus" :  10,
                "score" :  3,
        ]),
        
        ([      "name"  :  "油布包",
                "file"  :  "/d/mingjiao/obj/bag",
                "type"  :  "尋",
                "bonus" :  10,
                "score" :  3,
        ]),
        
        ([      "name"  :  "圍脖",
                "file"  :  "/d/mingjiao/obj/weibo",
                "type"  :  "尋",
                "bonus" :  10,
                "score" :  3,
        ]),
        
        ([      "name"  :  "骷髏頭骨",
                "file"  :  "/d/mobei/npc/obj/baigu",
                "type"  :  "尋",
                "bonus" :  10,
                "score" :  3,
        ]),
});

void create() { seteuid(getuid()); }

mapping query_job()
{
        return bangjobs[random(sizeof(bangjobs))];
}


