// /d/yixing/doc/info_guest.h
// Last Modified by winder on Jul. 12 2002

mapping *info_guest = ({
([      "name"  : "李克秀",
        "title" : "李提督",
        "file" : "/d/city/ymzhengting",
        "area"  : "揚州府",
        "bonus" : 30,
]),

([      "name"  : "陸高止",
        "title" : "陸師爺",
        "file" : "/d/city/ymzhengting",
        "area"  : "揚州府",
        "bonus" : 30,
]),

([      "name"  : "林震南",
        "title" : "林總鏢頭",
        "file" : "/d/city/zhengting",
        "area"  : "揚州福威鏢局",
        "bonus" : 20,
]),

([      "name"  : "趙良棟",
        "title" : "趙守備",
        "file" : "/d/city/bingyin",
        "area"  : "揚州兵營",
        "bonus" : 40,
]),

([      "name"  : "滕一雷",
        "title" : "滕大爺",
        "file" : "/d/changbai/nancheng",
        "area"  : "遼東",
        "bonus" : 150,
]),

([      "name"  : "焦文期",
        "title" : "焦三爺",
        "file" : "/d/changbai/tuyao",
        "area"  : "遼東",
        "bonus" : 170,
]),

([      "name"  : "赫爾蘇",
        "title" : "老把頭",
        "file" : "/d/changbai/tuwu",
        "area"  : "長白山",
        "bonus" : 170,
]),

([      "name"  : "忽倫大虎",
        "title" : "忽倫大爺",
        "file" : "/d/changbai/lyddao2",
        "area"  : "遼東",
        "bonus" : 140,
]),

([      "name"  : "鳳一鳴",
        "title" : "鳳少爺",
        "file" : "/d/foshan/yxhuiguan",
        "area"  : "佛山鎮",
        "bonus" : 60,
]),

([      "name"  : "戚長髮",
        "title" : "戚前輩",
        "file" : "/d/foshan/yard",
        "area"  : "湘西沅陵",
        "bonus" : 60,
]),

([      "name"  : "施琅",
        "title" : "施將軍",
        "file" : "/d/quanzhou/jiangfu1",
        "area"  : "泉州靖海侯府",
        "bonus" : 130,
]),

([      "name"  : "馬五德",
        "title" : "馬館主",
        "file" : "/d/quanzhou/qianting",
        "area"  : "泉州武館",
        "bonus" : 90,
]),

([      "name"  : "陳滸",
        "title" : "二當家",
        "file" : "/d/quanzhou/bangbu",
        "area"  : "泉州武館",
        "bonus" : 90,
]),

([      "name"  : "龍銓",
        "title" : "龍教頭",
        "file" : "/d/quanzhou/daobu",
        "area"  : "泉州武館",
        "bonus" : 90,
]),

([      "name"  : "劉虹瑛",
        "title" : "劉教頭",
        "file" : "/d/quanzhou/jianbu",
        "area"  : "泉州武館",
        "bonus" : 90,
]),

([      "name"  : "蕭飛",
        "title" : "蕭教頭",
        "file" : "/d/quanzhou/anqibu",
        "area"  : "泉州武館",
        "bonus" : 90,
]),

([      "name"  : "裘萬家",
        "title" : "裘少丐",
        "file" : "/d/shaolin/jiulou2",
        "area"  : "南陽城",
        "bonus" : 120,
]),

([      "name"  : "陸乘風",
        "title" : "陸莊主",
        "file" : "/d/taihu/shufang",
        "area"  : "太湖歸雲莊",
        "bonus" : 80,
]),

([      "name"  : "江百勝",
        "title" : "江隊長",
        "file" : "/d/taishan/nantian",
        "area"  : "泰山",
        "bonus" : 70,
]),

([      "name"  : "王小二",
        "title" : "王二爺",
        "file" : "/d/village/temple2",
        "area"  : "華山村玄壇廟",
        "bonus" : 150,
]),

([      "name"  : "馬光佐",
        "title" : "馬武師",
        "file" : "/d/xingxiu/btroad",
        "area"  : "白駝山莊",
        "bonus" : 50,
]),

([      "name"  : "歐陽克",
        "title" : "少莊主",
        "file" : "/d/xingxiu/bthill",
        "area"  : "白駝山莊",
        "bonus" : 80,
]),

([      "name"  : "尹克西",
        "title" : "賬房先生",
        "file" : "/d/xingxiu/btgate",
        "area"  : "白駝山",
        "bonus" : 180,
]),

([      "name"  : "歐陽鋒",
        "title" : "歐陽前輩",
        "file" : "/d/xingxiu/btroom",
        "area"  : "白駝山",
        "bonus" : 180,
]),

([      "name"  : "阿凡提",
        "title" : "阿凡提大叔",
        "file" : "/d/xingxiu/house1",
        "area"  : "伊犁城",
        "bonus" : 100,
]),

([      "name" : "胡老爺",
        "title" : "胡老爺",
        "file" : "/d/xingxiu/house",
        "area"  : "伊犁城",
        "bonus" : 100,
]),

([      "name"  : "獅吼子",
        "title" : "二師兄",
        "file" : "/d/xingxiu/tianroad2",
        "area"  : "星宿派",
        "bonus" : 120,
]),

([      "name"  : "天狼子",
        "title" : "三師兄",
        "file" : "/d/xingxiu/xxh1",
        "area"  : "星宿派",
        "bonus" : 120,
]),

([      "name"  : "丁春秋",
        "title" : "丁老仙",
        "file" : "/d/xingxiu/riyuedong",
        "area"  : "星宿派",
        "bonus" : 120,
]),

([      "name"  : "阿紫",
        "title" : "小師妹",
        "file" : "/d/xingxiu/tianroad3",
        "area"  : "星宿派",
        "bonus" : 120,
]),

([      "name"  : "出塵子",
        "title" : "八師兄",
        "file" : "/d/xingxiu/xxroad5",
        "area"  : "星宿派",
        "bonus" : 120,
]),

([      "name"  : "摘星子",
        "title" : "大師兄",
        "file" : "/d/xingxiu/cave",
        "area"  : "星宿派",
        "bonus" : 200,
]),

([      "name"  : "南海鱷神",
        "title" : "嶽老三",
        "file" : "/d/xixia/dawu",
        "area"  : "西夏",
        "bonus" : 250,
]),

([      "name"  : "葉二孃",
        "title" : "葉二孃",
        "file" : "/d/xixia/dawu",
        "area"  : "西夏",
        "bonus" : 250,
]),

([      "name"  : "一品堂武士",
        "title" : "武士",
        "file" : "/d/xixia/ypgate",
        "area"  : "西夏一品堂",
        "bonus" : 240,
]),

([      "name"  : "校尉",
        "title" : "校尉",
        "file" : "/d/xixia/jiangjunfu",
        "area"  : "靈州大將軍府",
        "bonus" : 240,
]),

([      "name"  : "勝諦",
        "title" : "勝諦上人",
        "file" : "/d/xueshan/shangu1",
        "area"  : "大雪山",
        "bonus" : 100,
]),

([      "name"  : "寶象",
        "title" : "寶象上人",
        "file" : "/d/xueshan/cave1",
        "area"  : "大雪山",
        "bonus" : 100,
]),

([      "name"  : "血刀老祖",
        "title" : "血刀老祖",
        "file" : "/d/xueshan/cave2",
        "area"  : "大雪山",
        "bonus" : 120,
]),

([      "name"  : "善勇",
        "title" : "善勇上人",
        "file " : "/d/xueshan/shixia",
        "area"  : "大雪山",
        "bonus" : 60,
]),
});
