//Cracked by Kafei
// 俠客行現在有以下大區域

mapping region_names = ([
	"baituo"   : "西域白駝山",
	"beijing"  : "北京",
	"changbai" : "關外長白山",
	"city"     : "揚州",
	"dali"     : "雲南大理",
	"death"    : "地獄",
	"emei"     : "四川峨嵋",
	"forest"   : "揚州郊外",
	"foshan"   : "廣東佛山",
	"gaibang"  : "丐幫所在地",
	"hangzhou" : "杭州",
	"huanghe"  : "黃河邊",
	"huangshan": "安徽黃山",
	"huashan"  : "華山",
	"island"   : "海外",
	"jiaxing"  : "嘉興",
	"kunlun"   : "崑崙山",
	"miaojiang": "雲南苗疆",
	"qilian"   : "祈連山",
	"quanzhou" : "福建泉州",
	"shaolin"  : "嵩山少林",
	"shenlong" : "遼東神龍島",
	"taihu"    : "太湖邊",
	"taishan"  : "山東泰山",
	"taohua"   : "東海桃花島",
	"village"  : "華山村",
	"wizard"   : "仙界",
	"wudang"   : "湖北武當山",
	"xiakedao" : "俠客島",
	"xingxiu"  : "西域",
	"xixia"    : "西夏",
	"xueshan"  : "藏邊大雪山",
	"zhongnan" : "終南山",
]);
